"""empty message

Revision ID: 7b6d9f2fc835
Revises: 
Create Date: 2025-12-06 21:45:51.054056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b6d9f2fc835'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorreading',
    sa.Column('sensor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_timestamp', sa.Integer(), nullable=False),
    sa.Column('received_timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sensor', 'recorded_timestamp')
    )
    op.create_index(op.f('ix_sensorreading_sensor'), 'sensorreading', ['sensor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensorreading_sensor'), table_name='sensorreading')
    op.drop_table('sensorreading')
    # ### end Alembic commands ###
