"""empty message

Revision ID: d00688190c22
Revises: 7b6d9f2fc835
Create Date: 2025-12-07 10:27:23.773584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd00688190c22'
down_revision: Union[str, Sequence[str], None] = '7b6d9f2fc835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorreading', sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorreading', 'method')
    # ### end Alembic commands ###
